---
- name: Update/upgrade packages
  apt:
    update_cache: yes
    upgrade: full
    name: "*"
    state: latest
  become: yes

- name: Install nodejs, npm, and pm2
  apt:
    name: nodejs
    state: latest
  npm:
    name: pm2
    global: yes
  become: yes
