---
- name: Create backend directory
  become: true
  file:
    path: ./backend
    state: directory

- name: Extract files
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: ./backend

- name: Create .env file
  ansible.builtin.lineinfile:
    dest: "./backend/.env"
    create: yes
    line: "{{ item }}"
  with_items: "{{ environment }}"

- name: Install npm dependencies
  shell: |
    cd ./backend
    npm i

- name: Starting the app with pm2
  shell: |
    pm2 stop default
    pm2 start npm -- start
