---
- name: Create backend directory
  file:
    path: ~/backend
    state: directory

- name: Extract files
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: Create permenant environment variables
  become: true
  ansible.builtin.lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ env_vars }}"

- name: Install npm dependencies
  shell: |
    cd ~/backend
    npm i
- name: Starting the app with pm2
  shell: |
    cd ~/backend
    pm2 stop default
    pm2 start dist/main.js

- name: Run pm2 as a service
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu