---
- name: Create backend directory
  file:
    path: ~/backend
    state: directory

- name: Extract files
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: Create .env file
  ansible.builtin.lineinfile:
    dest: "~/backend/.env"
    create: yes
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ env_vars }}"

- name: Install npm dependencies
  shell: |
    cd ~/backend
    npm i

- name: Starting the app with pm2
  shell: |
    cd ~/backend
    pm2 stop default
    pm2 delete all
    pm2 start npm -- start